### ISSUE TITLE
Boss scene

### ISSUE THREAD

**Issue by fedelway** [alexiscaspell/TgcJuego#1]
Una pregunta, es lo mismo sacar los meshes de las escenas que ya estan hechas? O sea, yo lo hice asi, no cree una scene nueva.

**Comment by alexiscaspell** [comment]
No entiendo a que te referis, una cosa son los meshes del mapa y otro los del boss.

**Comment by fedelway** [comment]
Digo, que yo para sacar los meshes del boss agarre uno ya existente. Pero esta bien, no lo mire bien. Solo le cambiaste el nombre digamos.
